import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getTwitterUserId } from '../src/services/api-services'

export default function Home() {

  const handleClick = () => {
    getTwitterUserId("SiddhiGate");
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <button onClick={handleClick}>Click me</button>
    </div>
  )
}
