import Head from 'next/head'
import Onboarding from '../src/components/Onboarding'
import Header from '../src/components/Header'

export default function Home() {
  return (
    <div className='container'>
      <Head>
        <title>devCase</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="icon" type="image/x-icon" href="./favicon.ico"></link>
      </Head>
      <Header />
      <div className='main'>
        <Onboarding />
      </div>
    </div>
  )
}
