import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { getGithubRepos, getTwitterUserId } from '../src/services/api-services'
import useGithub from '../src/hooks/useGithub'
import useHashnode from '../src/hooks/useHashnode'
import { useEffect, useState } from 'react'
import Github from '../src/components/GitHub'
import Hashnode from '../src/components/Hashnode'

export default function Home() {

 
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    {/* <Github/> */}

    <Hashnode/>
    </div>
  )
}
